const data = {
    products: [
        {
            _id: '1',
            name: 'Renault Kwid',
            category: 'mini SUV',
            image: '/images/p1.jpg',
            price: 4.07,
            brand: 'Renault',
            rating: 3,
            numReviews: 10,
            description: 'best budget car avialable',
        },
        {
            _id: '2',
            name: 'Hyundai Verna',
            category: 'Sedan',
            image: '/images/p6.jpg',
            price: 9.29,
            brand: 'Hyundai',
            rating: 4,
            numReviews: 38,
            description: 'Most Stylish Sedan',
        },
        {
            _id: '3',
            name: 'Honda Amaze',
            category: 'Sedan',
            image: '/images/p3.jpg',
            price: 6.34,
            brand: 'Honda',
            rating: 3,
            numReviews: 8,
            description: 'typical Indian sedan',
        },
        {
            _id: '4',
            name: 'Kia Seltos',
            category: 'SUV',
            image: '/images/p4.jpg',
            price: 9.95,
            brand: 'Kia',
            rating: 3,
            numReviews: 33,
            description: 'Stylish SUV from KIA',
        },
        {
            _id: '5',
            name: 'Toyota Fortuner',
            category: 'mini SUV',
            image: '/images/p5.jpg',
            price: 30.34,
            brand: 'RenaToyotault',
            rating: 4,
            numReviews: 58,
            description: 'best looking and solid build quality in SUV',
        },
        {
        _id: '6',
            name: 'Tata Harrier',
            category: 'SUV',
            image: '/images/p2.jpg',
            price: 14.4,
            brand: 'Tata',
            rating: 3.5,
            numReviews: 22,
            description: 'stylish car',
        },
    ],
};
export default data; 